### ISSUE TITLE
ERR trap executed when errexit is ignored

### ISSUE THREAD

**Issue by heftig** [oils-for-unix/oils#1654]
The bash manpage mentions:

> The `ERR` trap is not executed if the failed command is part of the command list immediately following a `while` or `until` keyword, part of the test in an `if` statement, part of a command executed in a `&&` or `||` list except the command following the final `&&` or `||`, any command in a pipeline but the last, or if the command's return value is being inverted using `!`. These are the same conditions obeyed by the `errexit` (`-e`) option.

Osh 0.16.0 apparently handles none of these conditions. In addition, some cases cause the trap to be run twice:

```sh
osh-0.16.0$ trap 'echo 1' ERR
osh-0.16.0$ echo 2 && false
2
1
1
osh-0.16.0$ echo >&2 2 | false
1
2
1
```

**Comment by bar-g** [comment]
Hi, concerning bash neglecting errors, maybe see:
https://www.oilshell.org/release/0.16.0/doc/error-handling.html

There are more error exit options in osh than in bash, also to print more info.
Some are automatically enabled in ysh, you could run your simple examples there.

**Comment by bar-g** [comment]
Ok, sorry, I see, from `shopt -p` even if verbose_errexit is enabled there is are no messages.

Yep, seems the ERR trap is not getting disabled together with `set +o errexit`.

**Comment by heftig** [comment]
I mean that the `ERR` trap shouldn't trigger for e.g. `if false; then`. That's just unhelpful.

**Comment by bar-g** [comment]
Yes, I see your point, now. Let's see what Andy responds.

Originally I had mistakenly assumed you had switched errorexit on in osh, and your problem were that ERR trap is executed twice, but that seems once for the single command, and once for the pipeline. Which is basicly fine, I think.

Another question is if it might make sense for oils-for-unix to internally prevent repeated execution of the same traps? And wether to always execute EXIT after other signals like (only?) bash. Maybe there is a good combination that obsoletes workarounds, and makes trap usage actually practical, by default.

**Comment by andychu** [comment]
Thanks for the report and for reproducing/confirming the bug -- that's especially helpful

The ERR feature is based on bash, and was implemented very recently, so it's probably just an oversight

**Comment by andychu** [comment]
This is now fixed, and will be out with the next release

It passes all these tests - http://op.oils.pub/github-jobs/7329/ovm-tarball.wwz/_tmp/spec/osh-py/builtin-trap-err.html

Feel free to test it out

@momiji has a pending PR for `set -o errtrace`

**Comment by andychu** [comment]
Released - https://www.oilshell.org/blog/2024/11/release-0.23.0.html
