### ISSUE TITLE
try builtin only sets _error sometimes, which is hard to remember and document

### ISSUE THREAD

**Issue by bar-g** [oils-for-unix/oils#1833]
I think the extended  `$_error` feature of `try` needs to fully support the subset of plain process status errors.

Or is there a reason for the new feature to be inconsistent with the old?

```
ysh ysh-0.20.0$ var list = [ ^(false), ^(echo $[toJ8( /d+/ )]) ]

ysh ysh-0.20.0$ for cmd in (list) { try (cmd); try echo $[_error.status] }
  for cmd in (list) { try (cmd); try echo $[_error.status] }
                                                  ^
[ interactive ]:2: fatal: Dict entry 'status' not found
ysh ysh-0.20.0$ 
```

**Comment by andychu** [comment]
Yeah OK, I think it is probably bad to make people remember `_status` vs. `_error.status` 

I think the design probably does need to be harmonized more

**Comment by bar-g** [comment]
Possibly relevant for harmonization:

`error` helper:
I can't find it now, but wasn't it said to be slow and not to be used in regular code paths (c++ exceptions)?

`die`:
I think I saw you're used to using something like that as a function

If the differences are relevant than maybe make them more apparent, e.g. as in having `stderr` (prints to stderr and continues with exit status), `fail` (exits execution) and `tracefail`?

**Comment by bar-g** [comment]
Hm, syntax differences resembling the body of experience about error handling? https://news.ycombinator.com/item?id=30430784

**Comment by andychu** [comment]
Regarding speed, it's a bit complex, but

- `error` builtin is indeed implemented with C++ exceptions.
  - they are fine when no error is thrown, or when the error is thrown and never caught
  - they are slow when the error is both thrown and caught
- However for **exterior** use cases, this shoudln't be noticeable.  The process itself is going to outweight any C++ exception slowness
- For **interior** use cases, it can be very slow relatively speaking.   If you write a tight loop checking with some kind of `Dict` access, and use `error` and catch it a lot, that's slow.  It's better to do explicit checks with if statements

So `error` is really for unexpected errors, not normal control flow.  Some errors are expected in a working program / environment

**Comment by andychu** [comment]
Fixed with https://github.com/oilshell/oil/commit/027ef039c329f3acbba56ab4c72c86ec07471a78

**Comment by andychu** [comment]
Released - https://www.oilshell.org/blog/2024/11/release-0.23.0.html
