### ISSUE TITLE
for loop that iterates over lines (buffered), document unbuffered idiom too

### ISSUE THREAD

**Issue by adigitoleo** [oils-for-unix/oils#1883]
Interesting project. One thing I hate about $SHELL is loops, in particular looping over command output or file contents. I think this kind of thing would make for a nice exampe. I tried to find it in various places on the website/in the docs but was not successful. I know you have `read --line` and `read --all`, but show me how to use them. In general the docs/examples needs more I/O stuff to my taste. Longer examples, in particular where looping might be involved.

At least I would hope that in ysh the syntax for loops is not as contrived as in $SHELL.

**Comment by adigitoleo** [comment]
Maybe I'm too optimistic about being able to shoot `xargs` into the sun. Another idea: some builtin version of GNU parallel would be nice in a world of multi-core CPUs. See also [this adaptation](https://github.com/rofl0r/jobflow).

**Comment by andychu** [comment]
Hi, thanks this is good feedback

Unfortunately we had to remove `read --line` for the reason here:

https://www.oilshell.org/blog/2024/03/release-0.21.0.html#breaking-changes

For now the idiom is to use shell `read -r`

```
while read -r line {  # unbuffered read
  echo $line
}
```

We also want

```
for line in < /dev/stdin other-file.txt > {
  echo $line
}
```

[#help-wanted > for loop that buffers lines](https://oilshell.zulipchat.com/#narrow/stream/417617-help-wanted/topic/for.20loop.20that.20buffers.20lines)

---

We can use help with that though, it's not on


- #1834

**Comment by andychu** [comment]
Also, I took a look at jobflow, it looks nice - https://github.com/rofl0r/jobflow/blob/master/jobflow.c

I now think something `xargs`-like  belongs in Oils -- anything that deals with parallel processes does

It will integrate better with tracing and the like

---

I realized it goes fairly well  with a test framework as well -- test cases should be run in parallel, selectable as a table,  and produce tables

**Comment by andychu** [comment]
The `for` loop was done for Oils 0.23.0 , which I unfortunately haven't written an announcement for -- http://www.oilshell.org/release/0.23.0/


It's now

```
for line in (io.stdin) {
  echo $line
}
```

and that also works with redirects

----

I still want to do something like xargs -- that is important!

**Comment by adigitoleo** [comment]
Thanks, I'll give oils a spin again soon. Sorry I wasn't able to help, got busy with job hunting... Maybe I'll have time again to think about the xargs implementation but I can't promise anything at this stage.

**Comment by andychu** [comment]
Please feel free to join Zulip -- all the dev discussion happens there!  We talk A LOT and then write A LITTLE code :-)

It is sort of our quirky style, but it appears to be working

---

Release announcement - https://www.oilshell.org/blog/2024/11/release-0.23.0.html
