### ISSUE TITLE
Remove INSTALL.html from /release/$VERSION page, point to oils-for-unix instructions

### ISSUE THREAD

**Issue by mtaran** [oils-for-unix/oils#1886]
## Repro

1. Be on a Mac (apple silicon if it matters) 13.5
2. Download https://www.oilshell.org/download/oils-for-unix-0.21.0.tar.gz from https://www.oilshell.org/release/0.21.0/
3. Open https://www.oilshell.org/release/0.21.0/doc/INSTALL.html
4. Copy paste the command to extract the tar file (it fails the first time since it's for the old/slow python version, but then I adjust it for the new C++ one)
5. ./configure completes quickly as expected
6. Afterwards I run `make`

## Expected

It makes something

## Actual

It errors with `make: *** No targets specified and no makefile found.  Stop.`

**Comment by andychu** [comment]
Oh see README-native.txt in the oils-for-unix tarball

Mentioned here: https://www.oilshell.org/blog/2024/03/release-0.21.0.html

Sorry INSTALL.html is a copy of INSTALL.txt, in the other tarball.  We will eventually get rid of it

We just switched to C++

Thanks for trying it!

**Comment by mtaran** [comment]
okay, I'll try that. but also, this info is kinda important so it'd be great to have it on https://www.oilshell.org/release/0.21.0/ (or at least link from that page to the blog announcement)

**Comment by andychu** [comment]
Agreed!  thank you for pointing this out

**Comment by andychu** [comment]
This was done with the last release

https://www.oilshell.org/release/0.22.0/

https://www.oilshell.org/release/0.22.0/doc/INSTALL.html

Thanks for the feedback!
