### ISSUE TITLE
Missing "Str=>lower()"

### ISSUE THREAD

**Issue by jtb20** [oils-for-unix/oils#1984]
Hi!

Probably a minor thing that got overlooked:

ysh ysh-0.22.0$ = "Hello"=>upper()
(Str)   "HELLO"
ysh ysh-0.22.0$ = "Hello"=>lower()
  = "Hello"=>lower()
             ^~~~~
[ interactive ]:2: fatal: Undefined variable 'lower'

**Comment by andychu** [comment]
Released - https://www.oilshell.org/blog/2024/11/release-0.23.0.html
