### ISSUE TITLE
mycpp doesn't root members of context managers 

### ISSUE THREAD

**Issue by andychu** [oils-for-unix/oils#1986]
Somehow I don't hit anything in ASAN, but GDB reveals the same problem in dbg/opt

```
[Detaching after fork from child process 629535]
[Detaching after fork from child process 629536]
[Detaching after fork from child process 629537]
[Detaching after fork from child process 629538]
[Detaching after fork from child process 629706]

Program received signal SIGSEGV, Segmentation fault.
0x00005555555d9a55 in state::Mem::SetNamed (this=0x5555557ce318, lval=<optimized out>, val=<optimized out>, which_scopes=which_scopes@entry=runtime_asdl::scope_e::LocalOnly, flags=flags@entry=0) at _gen/bin/oils_for_unix.mycpp.cc:26233
26233     if (((flags & SetNameref) or (flags & ClearNameref))) {
(gdb) 
(gdb) quit
A debugging session is active.

```

**Comment by jtb20** [comment]
It's a GC issue. The "restore" field in ctx_Shvar gets collected, and that makes ctx_Shvar::_Pop read uninitialised data and thus crash.

So the problem is sort of in Shvar::Run. I can fix it temporarily and badly by hacking the generated C++ source:

```
  {  // with
    ctx_Shvar *ctx = Alloc<ctx_Shvar>(this->mem, pairs);

    unused = this->cmd_ev->EvalCommand(cmd);
  }
```

i.e. because the pointers in ctx are never marked, so considered fair game to be swept. (I haven't audited anywhere else that might have the same problem, guess there might be though.)

(I haven't looked at the Python source for the generated file! Not sure if the fix is easier/harder there, or if this is a mycpp issue.)

HTH!

**Comment by jtb20** [comment]
(This "with ...:" idiom is used three times in pure_ysh.py, AFAICT.)

**Comment by andychu** [comment]
Thank you! This is very useful

I just reproduced the bug easily, by running replace() in a loop, which uses ctx_Shvar

We do test with a gcalways variant, not sure why that didn't catch this earlier, but we'll see

----

Also there seems to be a perf bug I also want to look into

**Comment by andychu** [comment]
I have a small reproducible case now, outside Oils

https://github.com/oilshell/oil/commit/cddb9f701e600f890151c840e2bfaa4fa2e4dbd1

OK good news is that this bug is not all that subtle ...  not sure what exactly the fix is yet

**Comment by jtb20** [comment]
Hi! I just tried out the 0.23.0 release and I'm still hitting this bug (or a very closely-related one). This reduced testcase still crashes:
```
#!/usr/bin/env ysh

proc p {
  var s = "hi"
  for q in (1..100) {
    shvar Q="whatever" {
      setvar s = "." ++ s
    }
  }
}

while (1) {
  p
}
```
I believe the problem is in ctx_Eval::ctx_Eval: it's possible for the 'restore' and 'dollar0_lval' members to be left uninitialised, which means they don't have the magic header needed for marking/sweeping. A dirty fix to the processed mycpp output can be done like this:
```
diff -urp oils-for-unix-0.23.0/_gen/bin/oils_for_unix.mycpp.cc oils-for-unix-0.23.0-dirty-fix/_gen/bin/oils_for_unix.mycpp.cc
--- oils-for-unix-0.23.0/_gen/bin/oils_for_unix.mycpp.cc        2024-08-25 10:45:35.000000000 -0500
+++ oils-for-unix-0.23.0-dirty-fix/_gen/bin/oils_for_unix.mycpp.cc      2024-09-03 13:34:31.051532409 -0500
@@ -26990,6 +26990,8 @@ ctx_Eval::ctx_Eval(state::Mem* mem, BigS
   if (dollar0 != nullptr) {
     this->dollar0_lval = Alloc<LeftName>(str1027, loc::Missing);
     mem->SetLocalName(this->dollar0_lval, Alloc<value::Str>(dollar0));
+  } else {
+    this->dollar0_lval = Alloc<LeftName>(str1027, loc::Missing);
   }
   if (pos_args != nullptr) {
     mem->argv_stack->append(Alloc<_ArgFrame>(pos_args));
@@ -26997,6 +26999,8 @@ ctx_Eval::ctx_Eval(state::Mem* mem, BigS
   if (vars != nullptr) {
     this->restore = Alloc<List<Tuple2<value_asdl::LeftName*, value_asdl::value_t*>*>>();
     this->_Push(vars);
+  } else {
+    this->restore = NewList<Tuple2<value_asdl::LeftName*, value_asdl::value_t*>*>();
   }
 }
```
HTH!

**Comment by jtb20** [comment]
(I suppose an alternative would be to only push the vars that are actually initialised, but then the destructor would need to pop 4-6 vars conditionally?)

**Comment by andychu** [comment]
Thanks for the report, and for narrowing it down -- and sorry you hit this again!  

It does look like the  fix was incomplete 

I think it is because `self.dollar0_lval` and `self.restore` are only "conditionally" members, which is valid in Python and not in C++.  And mycpp is not enforcing this condition!  

I think we need to enforce this everywhere

---

( @melvinw and @PossiblyAShrub  may be interested in this bug -- it is an instance of "invariants not checked" in mycpp -- which we should eventually get rid of --  https://www.oilshell.org/release/0.23.0/doc/oils-repo/mycpp/README.html )

**Comment by andychu** [comment]
OK I figured this out -- it is due to heap `Alloc<T>` having a special memset(0)

https://github.com/oils-for-unix/oils/blob/master/mycpp/gc_alloc.h#L141

But then the stack instantiation of the context manager doesn't have the same thing

I am changing all vars to simply be initialized, instead of the memset()!


---

Great bug, thank you!

I wonder if we can improve our testing to catch these somehow ... it does seem to take a few iterations

We do have a mode that GC's at every opportunity, I feel like it should have caught this

**Comment by jtb20** [comment]
Great, thank you for fixing it!

**Comment by andychu** [comment]
Released - https://www.oilshell.org/blog/2024/11/release-0.23.0.html
