### ISSUE TITLE
Add pp [x + 42] to print an expression and its value - like Rust dbg!()

### ISSUE THREAD

**Issue by andychu** [oils-for-unix/oils#1992]
We do it with reflection rather than a macro

```
$ var x = 1

$ pp [x + 42]
   x + 42 === 43
```

It can also handle a plain value

```

$ pp (x + 42)
    43
```

One question is if we actually do line wrapping ... hm

**Comment by andychu** [comment]
This is related to both the test framework and piping pretty printed output

https://oilshell.zulipchat.com/#narrow/stream/384942-language-design/topic/Can't.20pipe.20output.20of.20pretty.20printing.20to.20less.20-r


```
pp (x) | less -r
```

**Comment by justinpombrio** [comment]
### Planned behavior of pp

These can be spec tests in `spec/ysh-builtin-meta`.

    var x = 2
    pp (x + 1)  # prints "3" (same as `= x + 1`)
    pp [x + 1]  # prints "x + 1 === 3"

    proc my-pp (; val)  {
      pp (val)
    }
    my-pp (x + 1)  # same as `pp (x + 1)` -- "3"
    my-pp [x + 1]  # same as `pp [x + 1]` -- "x + 1 === 3"
    my-pp (^[x + 1])  # same as above

### Implementation

- [ ] Store a `List[SourceLine]` in `core/value.asdl Expr`.
- [ ] Use the logic of `SnipCodeBlock` to print the lines (in an internal method on Expr). Share code as appropriate.
- [ ] Have `pp (expr)` evaluate and then print the expr (using the printing style of `=`).
- [ ] Have `pp [expr]` evaluate the expr, then print "$EXPR == $VALUE".
- [ ] Spec tests.

**Comment by andychu** [comment]
I  landed a version of this morning that does not quote code like SnipCodeBlock().  Instead it reuses the ability to quote specific lines

https://github.com/oils-for-unix/oils/commit/d3f6fa14cc40655c88da9cdcc82db3a0138cdffb

I guess the issue is that Tokens points to lines, which is kind of "good enough"

It's non-trivial to get the line  AFTER the one that a Token points to, because of our graph-shaped AST.  And in general, expressions can span multiple lines.

But it is easy to get the line for a token -- it's a field on the Token, and Tokens are attached to most AST nodes


---

I think we still need solve that problem, but I hit this fairly hard when writing real YSH code, so I did something minimal

Feedback is welcome

**Comment by andychu** [comment]
Released - https://www.oilshell.org/blog/2024/11/release-0.23.0.html
