### ISSUE TITLE
`json read` unexpectedly parses `123\x00`

### ISSUE THREAD

**Issue by ellen364** [oils-for-unix/oils#2026]
This is a test case from [nst/JSONTestSuite](https://github.com/nst/JSONTestSuite/blob/master/test_parsing/n_multidigit_number_then_00.json) that is expected to fail but that passes in ysh.

```bash
# file contains 123\00
json read < n_multidigit_number_then_00.json
echo $_reply
# output: 123
```

Expected output is a parse error. JSON does not allow `\00` in numbers and numbers are a value, which must be followed by whitepsace.

## An inconsistency in ysh?

Curiously, the `toJson()` and `toJson8()` functions do both error, as they should. I'd have liked an error message that mentions JSON parsing, but that's a "nice to have".

```bash
echo $[toJson(123\00)]
# output: [ interactive ]:23: Syntax error in expression (near Id.Char_OneChar)
```

## Other implementations 

Python:

```python
import json

with open("n_multidigit_number_then_00.json") as f:
    json.load(f)
   # output: json.decoder.JSONDecodeError: Extra data: line 1 column 4 (char 3) 
```

JavaScript:

```js
JSON.parse('123\00');
// output: Uncaught SyntaxError: JSON.parse: unexpected non-whitespace character after JSON data at line 1 column 4 of the JSON data
```

**Comment by andychu** [comment]
OK yes this is interesting!



```
ysh$ = fromJson(b'123\y00')
(Int)   123


ysh$ = fromJson(b'123\y01')
  = fromJson(b'123\y01')
            ^
[ interactive ]:21: fatal: Unexpected trailing input (line 1, offset 3-4: '123\x01')

```

(in shell, the 0 byte is written  like `$'\x00'` (bash)   or `b'\y00'   (YSH, j8 notation)`

**Comment by ellen364** [comment]
That's a much better example, thanks. Confused myself and pasted a `toJson()` example that isn't relevant.

I've been finding `fromJson()` confusing generally. Here's a sequence of errors that I got while trying to work it out.

```bash
fromJson('123\00')
# [ interactive ]:34: Space required before  (
```
Forgot  the `=` at the start. Misleading error but not relevant to JSON parsing.

```bash
= fromJson('123\00')
# [ interactive ]:35: Strings with backslashes should look like r'\n' or u'\n'  or b'\n'

= fromJson(b'123\00')
# [ interactive ]:36: Invalid char escape in C-style string literal (OILS-ERR-11)
```

That last one really puzzles me. I can see from your examples that it needs to be `b'123\y01'` and that works for me in the shell. (In the sense that I don't any syntax errors and the JSON is parsed, even if the parsing is unexpected per the spec .) But the test file contains `b'123\00'` without the `y`.so I guess `json read` is doing something extra to handle that.

**Comment by andychu** [comment]
Oh yes "space before (" is probably something that people will run into ... (or multiple people already did IIRC)

 I think at the very least we need an OILS-ERR to suggest expression mode. Or maybe I can put it right in the error message.

**Comment by andychu** [comment]
I actually don't see where got the syntax `123\00` ?  How did you derive that from the test file?

https://github.com/nst/JSONTestSuite/blob/master/test_parsing/n_multidigit_number_then_00.json

---

e.g. I see this:

$ cat n_multidigit_number_then_00.json  | python3 -c 'import sys; print(repr(sys.stdin.read()))'
'123\x00'

In OSH it's this:

```
$ cat n_multidigit_number_then_00.json  | osh -c 'read --all; = _reply'
(Str)   "123\u0000"
```

which reminds me that we have a design issue there, we need to print it as `b'123\y00', which is what I entered back into the interpreter

----

In any case, this bug is great, thanks!

**Comment by ellen364** [comment]
Hmm, perhaps I've also found a bug (or at least a pretty printing oddity) in whatever application Debian Bookwork calls `Text Editor`.

The `\00` seemed strange to me too, but it's what I get when going to the file in Github, clicking "download raw file" and then opening in Text Editor. (Which was how I did an initial glance at the file and have repeated now to confirm.) Text Editor seems to mangle the presentation, dropping the `x`, and it stays mangled when copy pasting.

**Comment by andychu** [comment]
This also happens if there is data AFTER the nul

so yeah this is a bug ...


```
ysh andy@hoover:~/git/oilshell/oil$ = fromJson(b'123\y00ab')
(Int)   123
ysh andy@hoover:~/git/oilshell/oil$ = fromJson(b'123\y01ab')
  = fromJson(b'123\y01ab')
            ^
[ interactive ]:3: fatal: Unexpected trailing input (line 1, offset 3-4: '123\x01ab')

```

**Comment by andychu** [comment]
OK I see, the bug is because  `\x00` is `Id.Eol_Tok` 

We have a trailing input check, but it checks the token

This should be easy to fix

**Comment by andychu** [comment]
Fixed, this will be out with the next release

Thanks!

**Comment by andychu** [comment]
Released - https://www.oilshell.org/blog/2024/11/release-0.23.0.html
