### ISSUE TITLE
Add support for HEAD in brew configuration of oils-for-unix

### ISSUE THREAD

**Issue by ale5000-git** [oils-for-unix/oils#2116]
Please add support for `HEAD` in `brew` configuration of `oils-for-unix`.

It would be nice to be able to do this:
`brew install --HEAD --build-from-source 'oils-for-unix'`

Other projects support it.

**Comment by andychu** [comment]
This should be a request toward `brew` , or a contribution

As far as I know, no  current Oils contributors use brew
