### ISSUE TITLE
`install-wedges` is mentioned in docs, but no longer exists in `build/deps.sh`

### ISSUE THREAD

**Issue by KingMob** [oils-for-unix/oils#2124]
There are subvariants, like `install-wedge-list`, `install-wedges-fast`, and `install-wedges-soil`, but plain `install-wedges` doesn't exist.

It's mentioned in `mycpp/README.md`, `soil/worker.sh`, and the dev cheat sheet in the wiki.

The only reason I didn't go ahead and fix them is, I'm not sure which to replace the references with.

**Comment by andychu** [comment]
Thanks for noticing this!  I just renamed it back to `install-wedges`


(I optimized it awhile ago and the new version was called `install-wedges-fast`, but I didn't rename it back !)
