### ISSUE TITLE
Undocumented osh - bash incompatibility with stdout and stderr redirection

### ISSUE THREAD

**Issue by mateon1** [oils-for-unix/oils#2170]
The following two lines are equivalent in bash, but the latter causes a syntax error in osh:
```bash
osh-0.22.0$ sh -c 'echo >&2 foo bar; echo baz' &> >(xxd)
00000000: 666f 6f20 6261 720a 6261 7a0a            foo bar.baz.
osh-0.22.0$ sh -c 'echo >&2 foo bar; echo baz' >& >(xxd)
  sh -c 'echo >&2 foo bar; echo baz' >& >(xxd)
                                        ^~
[ interactive ]:2: Invalid descriptor '/dev/fd/5'.  Expected D, -, or D- where D is an integer
```

This can be either fixed by parsing the redirection as an stdout and stderr redirection if anything except a digit or - is encountered after `>&`, making it compatible with bash, or documenting the difference since there's a trivial workaround by changing to the first redirection format.

**Comment by mateon1** [comment]
Just noticed that I used the wrong nixpkgs to install oils-for-linux, so I used an outdated version. I can confirm the exact same behavior on oils-for-linux 0.24.0 osh

**Comment by mateon1** [comment]
To answer the questions, I discovered this by reading the bash manpage and trying it out in several shells, including osh.

From bash 5.2 manpage:

>    Redirecting Standard Output and Standard Error
>        This  construct allows both the standard output (file descriptor 1) and the standard error output (file descriptor 2) to be redirected to the file whose name is the expansion of word.
> 
>        There are two formats for redirecting standard output and standard error:
> 
>               &>word
>        and
>               >&word
> 
>        Of the two forms, the first is preferred.  This is semantically equivalent to
> 
>               >word 2>&1
> 
>        When using the second form, word may not expand to a number or -.  If it does, other redirection operators apply
>        (see Duplicating File Descriptors below) for compatibility reasons.
> 

I don't know if this causes any practical breakage. (`|&` and `echo -E` cause much more breakage for my personal scripts, couldn't find an issue for the former because symbol-only searches are hard, latter has #1843)

**Comment by andychu** [comment]
OK thank you, I'm going to move this to #746

I think it's fine to have this in OSH, though we would probably need a contribution for it
