### ISSUE TITLE
Py/Mojo as Py/C++ alternative 

### ISSUE THREAD

**Issue by nisbet-hubbard** [oils-for-unix/oils#2182]
Mojo seems to provide another good translation target once the tooling is ready.

WIP: https://github.com/msaelices/py2mojo

**Comment by andychu** [comment]
I encourage any parallel experiments with our codebase :)  

I know a bit about Mojo, and I think it's a great project, though I don't think it's right for Oils. But somebody with more knowledge could change that

People have started rewriting it in Nim, and in Rust, so anything is fair game

**Comment by andychu** [comment]
This topic is better as a Zulip discussion, and someone would need to kick it off, etc.
