### ISSUE TITLE
${foo:} is allowed in OSH, but not in bash (slicing)

### ISSUE THREAD

**Issue by andychu** [oils-for-unix/oils#2196]
Reported by Sean

https://oilshell.zulipchat.com/#narrow/channel/202008-oil-documentation/topic/OSH.20Parses.20Shell.20Scripts.20Up.20Front.20in.20a.20Single.20Pass

**Comment by akinomyoga** [comment]
In my understanding, this was intentionally allowed in commit 986a39e09d963cb741acd25a6328892bd7e275ad after a discussion at [(81) #oil-discuss &gt; ${arr[@]::} in bash - is it documented? - Oils - Zulip](https://oilshell.zulipchat.com/#narrow/channel/121540-oil-discuss/topic/.24.7Barr.5B.40.5D.3A.3A.7D.20in.20bash.20-.20is.20it.20documented.3F/near/447229187).

**Comment by andychu** [comment]
Wow, thank you for pointing that out!  I completely **forgot** about this

```
$ bash -c 'echo ${foo:}'
bash: line 1: ${foo:}: bad substitution

$ bash -c 'echo ${foo: }'

$ bash -c 'echo ${foo[@]:}'
bash: line 1: ${foo[@]:}: bad substitution

$ bash -c 'echo ${foo[@]: }'


```

So yeah I think it is probably fine to keep it -- I don't want to have the space make a difference

**Comment by andychu** [comment]
Instead of changing OSH, I patched the old post instead: https://www.oilshell.org/blog/2016/10/13.html

`${foo.}` is a syntax error

We don't want to make spaces significant

Thanks for the reminder!
